version: "3.9"

services: 
  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - 1234:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      do_kub_network:
        aliases:
          - proxy-name
    depends_on:
      - backend
      - frontend

  backend:  
    env_file: ./.env
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports: 
      - "3000:3000"
    networks:
      do_kub_network:
        aliases:
          - backend-name


  frontend:  
    env_file: ./.env
    build: 
      context: ./frontend/
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports: 
      - "8080:8080"
    networks:
      do_kub_network:
        aliases:
          - frontend-name

  postgres:
    image: postgres
    container_name: pg-container
    ports:      
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "testpassword"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      do_kub_network:
        aliases:
          - psql

networks:
  do_kub_network:
